apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  labels:
    {{- include "telegram-prober.labels" . | nindent 4 }}
  name: {{ include "telegram-prober.fullname" . }}-probe
  namespace: {{ .Values.namespace }}
spec:
  interval: {{ .Values.prober.interval }}
  jobName: {{ include "telegram-prober.fullname" . }}
  module: https_2xx
  prober:
    path: /probe
    scheme: http
    url: {{ include "telegram-prober.fullname" . }}:80
  scrapeTimeout: 10s
  targets:
    staticConfig:
      static:
        {{- with .Values.prober.targets }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
