apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telegram-prober.fullname" . }}-secret
  labels:
    {{- include "telegram-prober.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
    TELEGRAM_API_ID: "{{ .Values.telegramAccountConfig.api_id }}"
    TELEGRAM_API_HASH: "{{ .Values.telegramAccountConfig.api_hash }}"
    TELETHON_SESSIONS: "{{- join "," .Values.telegramAccountConfig.sessions }}"
